#!/usr/bin/env python3
# =====================================================================
# smoke_wrappers.py -- assemble every cx.* wrapper, one program per gate.
#
# The examples exercise maybe a tenth of the wrapper. The rest is only
# ever proven when somebody calls it -- and a wrapper that names a symbol
# the inline asm cannot see, or that the library's own source cannot
# assemble, fails at build time in that person's program, not here.
#
# So: for each X16_USE_* gate, write a program that calls every wrapper
# belonging to it (arguments are all zero -- nothing runs, this is an
# assembly test) and build it through build.ps1, exactly as a real
# program is built, gate scan and all.
#
#   python tools\smoke_wrappers.py                 # all gates
#   python tools\smoke_wrappers.py X16_USE_STACK   # named gates only
#
# Prints one line per gate and the assembler's last words for each
# failure. Exit status is the number of gates that failed.
# =====================================================================
import json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
PKG  = os.path.join(ROOT, "x16lib")
GEN  = os.path.join(ROOT, "build", "smoke")

def load():
    gates = json.load(open(os.path.join(PKG, "routine_gates.json")))
    sigs = {}
    for line in open(os.path.join(PKG, "x16lib.p8"), encoding="utf-8"):
        m = re.match(r"^    sub ([a-z0-9_]+)\((.*?)\)(\s*->\s*\w+)?\s*\{", line)
        if m:
            args = [a.strip() for a in m.group(2).split(",") if a.strip()]
            sigs[m.group(1)] = (len(args), bool(m.group(3)))
    by_gate = {}
    for name, gate in gates.items():
        if name in sigs:                     # load_banks has no gate
            by_gate.setdefault(gate, []).append(name)
    return by_gate, sigs

def program(routines, sigs):
    body = []
    for r in sorted(routines):
        nargs, has_ret = sigs[r]
        # a return value must be consumed or discarded; Prog8 says so
        body.append(f"        {'void ' if has_ret else ''}cx.{r}("
                    + ", ".join("0" for _ in range(nargs)) + ")")
    return ("; GENERATED by tools/smoke_wrappers.py -- assembly test only.\n"
            "%import x16lib\n%import x16lib_const\n%zeropage dontuse\n\n"
            "main {\n    sub start() {\n" + "\n".join(body) + "\n    }\n}\n")

def main():
    by_gate, sigs = load()
    os.makedirs(GEN, exist_ok=True)
    wanted = sys.argv[1:] or sorted(by_gate)
    unknown = [g for g in wanted if g not in by_gate]
    if unknown:
        sys.exit("no such gate: " + ", ".join(unknown))

    fails, total = [], 0
    for gate in wanted:
        routines = by_gate[gate]
        total += len(routines)
        path = os.path.join(GEN, gate.lower() + ".p8")
        open(path, "w", newline="\n").write(program(routines, sigs))
        p = subprocess.run(["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                            "-File", os.path.join(ROOT, "build.ps1"), "-Program", path],
                           capture_output=True, text=True, cwd=ROOT)
        ok = p.returncode == 0 and "Built " in p.stdout
        print(f"{'ok  ' if ok else 'FAIL'} {gate:34s} {len(routines):3d} routines",
              flush=True)
        if not ok:
            fails.append((gate, p.stdout + p.stderr))

    print(f"\n{total} wrappers over {len(wanted)} gate(s); {len(fails)} failed")
    for gate, log in fails:
        print(f"\n===== {gate} =====")
        errs = [l for l in log.splitlines() if "error:" in l or "Error" in l]
        print("\n".join(errs[:12] if errs else log.splitlines()[-15:]))
    return len(fails)

if __name__ == "__main__":
    sys.exit(main())
